### PR TITLE
Fix data race in Tier.go Announce method and torrentsByInfoHash session member variable access

### LINKED ISSUE #25: Data race in Tier.go Announce method
I have 2 sessions objects, and I run a download for both.

Here is the race report.

```
==================
WARNING: DATA RACE
Read at 0x00c000666678 by goroutine 81:
  github.com/cenkalti/rain/internal/tracker.(*Tier).Announce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/tracker/tier.go:27 +0xb9
  github.com/cenkalti/rain/internal/announcer.announce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/announce.go:24 +0x18f
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).announce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:244 +0x1fc
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).doAnnounce·dwrap·5()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:238 +0x6e

Previous write at 0x00c000666678 by goroutine 151:
  github.com/cenkalti/rain/internal/tracker.(*Tier).Announce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/tracker/tier.go:29 +0x1c4
  github.com/cenkalti/rain/internal/announcer.announce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/announce.go:24 +0x18f
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).announce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:244 +0x1fc
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).doAnnounce·dwrap·5()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:238 +0x6e

Goroutine 81 (running) created at:
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).doAnnounce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:238 +0x110
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).Run()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:209 +0x10ec
  github.com/cenkalti/rain/torrent.(*torrent).startNewAnnouncer·dwrap·45()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/torrent/torrent_start.go:107 +0x39

Goroutine 151 (finished) created at:
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).doAnnounce()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:238 +0x110
  github.com/cenkalti/rain/internal/announcer.(*PeriodicalAnnouncer).Run()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/internal/announcer/periodic.go:156 +0x284
  github.com/cenkalti/rain/torrent.(*torrent).startNewAnnouncer·dwrap·45()
      /var/lib/jenkins/go/pkg/mod/github.com/cenkalti/rain@v1.7.0/torrent/torrent_start.go:107 +0x39
==================
```

If I read this right, the problem is in this file

```
// Announce a torrent to the tracker.
// If annouce fails, the next announce will be made to the next Tracker in the tier.
func (t *Tier) Announce(ctx context.Context, req AnnounceRequest) (*AnnounceResponse, error) {
    resp, err := t.Trackers[t.index].Announce(ctx, req) // line 27
    if err != nil {
        t.index = (t.index + 1) % len(t.Trackers) // line 29
    }
    return resp, err
}
```

on line 27 and 29 we are reading/writing t.index.
Maybe a fix would be to make t.index an atomic int, and use atomic operations to get/set it ?

Or maybe the problem is with the t.Trackers array ? I will try to something obvious (like adding a mutex to Tier) to debug this further.

### PR DESCRIPTION
**Pull request by bsergean**
Fix #25 by adding a mutex. There is probably a more lightweight approach (atomic) but that does fix the data race in my unittest.

### CODE REVIEW

**Comment by cenkalti** [comment]
Hi @bsergean . Thanks for you PR. I think it is not good here to protect the method with a lock because `Announce` is a blocking function. Can you update it to use `sync/atomic` here?

**Comment by bsergean** [comment]
I will try to just protect the t.index member, and also we can record the len(of the index) as a member variable, this way we don’t need to query it.

**Comment by bsergean** [comment]
Here we go the latest change uses an atomic instead of a mutex.

**Comment by bsergean** [comment]
@cenkalti does the new implementation look better to you ?

**Comment by BatuAksoy** [comment]
Just a question, I wonder is there a guarantee between two atomic operations? In my opinion that racing may still be the case here:
```
Goroutine 1             Goroutine 2
Load(x=5)
                        Load(x=5)
Some calculation(x=6)   Some calculation(x=6)    -> they will have same value here because Load operations resulted in same value.
Store(x=6)
                        Store(x=6)    -> instead of x=7
```
Any opinions?

**Comment by bsergean** [comment]
Just tweaked the code a little bit, I’m not sure it is now correct but it feels better.

**Comment by cenkalti** [comment]
@BatuAksoy you are right. I have replaced the increment statement with a `CompareAndSwap` operation:
https://github.com/cenkalti/rain/commit/7ef76bea2ea4a0527820ab4a3f6be8fbd5de809a#diff-acef4f98f685c29df43c712b22337dff0ec8ae76768b3dd57d7708f5155fcb21R34

@bsergean I have made a refactor over your commit:
7ef76bea2ea4a0527820ab4a3f6be8fbd5de809a

**Pull request closed without merging**
